// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tenqgtcuuoscbnoynpzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbnFndGN1dW9zY2Jub3lucHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjI1OTksImV4cCI6MjA2MDM5ODU5OX0.UPBfgeIG6lVW8BHtOze9ebFJxuK-I2FBhehWYaKZ87E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);